### ISSUE TITLE
Update readme.md with more information 

### ISSUE THREAD

**Issue by pacheco7** [se38/abapFaker#3]
Hi @se38!

Can I help to improve the readme.md file with more information?

**Comment by se38** [comment]
I would be happy if you can help me with a better documentation. Currently I'm a bit busy.
Thank you!

**Comment by pacheco7** [comment]
Pull request #6 opened for the documentation update. Also, this can be accessed on the URL: https://abapfaker.readthedocs.io/en/latest/

**Comment by se38** [comment]
Merged.
A big thank you.
