### ISSUE TITLE
Improvement of demo program

### ISSUE THREAD

**Issue by pacheco7** [se38/abapFaker#4]
Hi @se38,

I have a proposal for the demo program. When we acquiring more languages, the current program will not serve to all.

My proposal is to do the following statements:

REPORT z_abap_faker_demo.

CLASS app DEFINITION CREATE PUBLIC.
  PUBLIC SECTION.
    METHODS main.
ENDCLASS.

PARAMETERS: lang TYPE zelang.

NEW app( )->main( ).

CLASS app IMPLEMENTATION.
  METHOD main.
    cl_demo_output=>new( )->begin_section( |ABAP Faker|
                         )->write( VALUE stringtab( LET faker = NEW zcl_faker( CONV #( lang ) ) in
                                                    FOR I = 1 UNTIL i > 10
                                                    ( |{ faker->person->name( ) }\n| &&
                                                      |{ faker->address->street_address( ) }\n| &&
                                                      |{ faker->address->city_address( ) }\n\n| &&
                                                      |Phone { faker->phone->number( ) }\n| &&
                                                      |{ faker->company->company_name( ) }\n| &&
                                                      |{ faker->job->job_title( ) }\n| &&
                                                      |{ sy-uline }| ) )
                         )->display( ).
  ENDMETHOD.
ENDCLASS.

What you think about it? 

Best regards.

**Comment by se38** [comment]
I think we need two parameters: language (please use already existing data element LANGUAGEISO which is a char02 field and contains already a value help) and country -> pt_BR

(nice usage of the new ABAP language features by the way...)

```
    cl_demo_output=>new( )->begin_section( |ABAP Faker|
      )->write( VALUE stringtab( LET faker = NEW zcl_faker( |{ to_lower( p_langu ) }_{ p_cntry }| )
        IN FOR i = 1 UNTIL i > 10
        ( |{ faker->person->name( ) }\n| &&
          |{ faker->address->street_address( ) }\n| &&
          |{ faker->address->city_address( ) }\n\n| &&
          |Phone { faker->phone->number( ) }\n| &&
          |{ faker->company->company_name( ) }\n| &&
          |{ faker->job->job_title( ) }\n| &&
          |{ sy-uline }| ) )
    )->display( ).
```

Let's do it :-)

**Comment by pacheco7** [comment]
Pull request #5 opened to review. ;)

**Comment by se38** [comment]
Merged
